<?xml version="1.0" encoding="utf-8"?><Database Name="SeProject" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2D1HUID;Initial Catalog=SeProject;Integrated Security=True" SettingsObjectName="Project.Properties.Settings" SettingsPropertyName="SeProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="S_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="S_Timein" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="S_Timeout" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="DID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_Schedule" Member="Doctor" ThisKey="DID" OtherKey="DID" Type="Doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="A_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="A_Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="DID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Appointment" Member="Customer" ThisKey="PID" OtherKey="PID" Type="Customer" IsForeignKey="true" />
      <Association Name="Doctor_Appointment" Member="Doctor" ThisKey="DID" OtherKey="DID" Type="Doctor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Father_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Marital_Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastappointment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lastdoctor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Diagnosis" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bio" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Customer_Appointment" Member="Appointments" ThisKey="PID" OtherKey="PID" Type="Appointment" />
      <Association Name="User_Customer" Member="User" ThisKey="uid" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="DID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Father_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Specialization" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Experience" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Bio" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Doctor_Schedule" Member="Schedules" ThisKey="DID" OtherKey="DID" Type="Schedule" />
      <Association Name="Doctor_Appointment" Member="Appointments" ThisKey="DID" OtherKey="DID" Type="Appointment" />
      <Association Name="User_Doctor" Member="User" ThisKey="uid" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Registered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Doctor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Reserved" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Customer" Member="Customers" ThisKey="UserID" OtherKey="uid" Type="Customer" />
      <Association Name="User_Doctor" Member="Doctors" ThisKey="UserID" OtherKey="uid" Type="Doctor" />
    </Type>
  </Table>
</Database>